dataset_type: "tiny_nerf" # [tiny_nerf, custom, blender]
dataset_path: "data/lego_200x200.npz"
ckpt_path: "checkpoints/lego_nerf_checkpoint.pt"

# nerf parameters
rays_per_batch: 2000
near: 2.0
far: 6.0
samples_per_ray: 64
perturb_samples: True
t_thresh: 0.0

# training parameters
lr: 0.001
lr_decay_interval: 2000
epochs: 6000
val_interval: 200
save_interval: 500